### ISSUE TITLE
代码写错了吧

### ISSUE THREAD

**Issue by zouhe0** [xyazh/monty-hall-problem-for-python#1]
你popFalse门的时候错了，更正代码
`import random

def raffleDoor(change = False):
    n = 1000000
    r = 0
    for _ in range(n):
        #随机生成三个门，其中一个为T另外两个为F
        number = random.randint(0,2)
        doors = [i==number for i in range(3)]

        #先随机打开一个门
        ext = doors.pop(random.randint(0,2))

        #排除一个假的门
        s = 0
        for i in range(2):
            if doors[i] == True:
                s=1
        if s==1:
            doors=[True]
        else:
            doors=[False]
        #是否要换
        if change:
            ext = doors[0]

        #记录结果
        if ext:
            r += 1

    return r/n

if __name__ == "__main__":
    print(raffleDoor())
    print(raffleDoor(True))`

**Comment by xyazh** [comment]
感谢你的意见
我确实注意到一些逻辑上的疏忽
已修复
